name: Build Beat App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip beat-making-app.zip
          ls

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install packages
        run: |
          cd beat-making-app
          npm install

      - name: Build project
        run: |
          cd beat-making-app
          npm run build
